import type { KhoanPhiRow } from '../types/domain'

/** Dữ liệu danh mục phí mẫu cố định (deterministic) — tên/số tiền/đơn vị tham khảo cách đặt
 * ở module Danh mục Phí bên dashportal (Sở), dùng để Tab "Danh sách danh mục phí" có sẵn dữ
 * liệu khi demo lần đầu. */
export function buildDanhMucPhiSeed(nienKhoa: string): KhoanPhiRow[] {
  const rows: Omit<KhoanPhiRow, 'nienKhoa'>[] = [
    {
      maPhi: 'HP001',
      tenPhi: 'Học phí tháng',
      soTien: 500000,
      donViTinh: 'tháng',
      nguonThu: 'Học phí',
      nhomPhi: 'Thu theo tháng',
      danhMucKhoanThu: 'Học phí',
      thamChieuPhapLy: 'NQ 04/2023/NQ-HĐND',
      ghiChu: 'Thu theo học kỳ',
    },
    {
      maPhi: 'BT001',
      tenPhi: 'Bán trú',
      soTien: 300000,
      donViTinh: 'tháng',
      nguonThu: 'Bán trú',
      nhomPhi: 'Thu theo tháng',
      danhMucKhoanThu: 'Bán trú',
      thamChieuPhapLy: '',
      ghiChu: '',
    },
    {
      maPhi: 'DD001',
      tenPhi: 'Đưa đón xe buýt',
      soTien: 250000,
      donViTinh: 'tháng',
      nguonThu: 'Dịch vụ',
      nhomPhi: 'Thu theo tháng',
      danhMucKhoanThu: 'Đưa đón',
      thamChieuPhapLy: '',
      ghiChu: '',
    },
    {
      maPhi: 'BH001',
      tenPhi: 'Bảo hiểm y tế học sinh',
      soTien: 680000,
      donViTinh: 'năm',
      nguonThu: 'Dịch vụ',
      nhomPhi: 'Thu theo năm',
      danhMucKhoanThu: 'Bảo hiểm y tế',
      thamChieuPhapLy: 'NĐ 81/2021/NĐ-CP',
      ghiChu: '',
    },
    {
      maPhi: 'DP001',
      tenPhi: 'Đồng phục học sinh',
      soTien: 450000,
      donViTinh: 'lần',
      nguonThu: 'Dịch vụ',
      nhomPhi: 'Thu không định kỳ',
      danhMucKhoanThu: 'Đồng phục',
      thamChieuPhapLy: '',
      ghiChu: '2 bộ/năm',
    },
    {
      maPhi: 'NK001',
      tenPhi: 'Ngoại khoá tiếng Anh',
      soTien: 400000,
      donViTinh: 'tháng',
      nguonThu: 'Dịch vụ',
      nhomPhi: 'Thu theo tháng',
      danhMucKhoanThu: 'Ngoại khoá',
      thamChieuPhapLy: '',
      ghiChu: '',
    },
    {
      maPhi: 'NK002',
      tenPhi: 'Ngoại khoá kỹ năng sống',
      soTien: 350000,
      donViTinh: 'tháng',
      nguonThu: 'Dịch vụ',
      nhomPhi: 'Thu theo tháng',
      danhMucKhoanThu: 'Ngoại khoá',
      thamChieuPhapLy: '',
      ghiChu: '',
    },
    {
      maPhi: 'KT001',
      tenPhi: 'Quỹ khuyến học',
      soTien: 100000,
      donViTinh: 'năm',
      nguonThu: 'Học phí',
      nhomPhi: 'Thu theo năm',
      danhMucKhoanThu: 'Khoản thu khác',
      thamChieuPhapLy: '',
      ghiChu: 'Tự nguyện',
    },
    {
      maPhi: 'HP002',
      tenPhi: 'Học phí học kỳ 2',
      soTien: 500000,
      donViTinh: 'tháng',
      nguonThu: 'Học phí',
      nhomPhi: 'Thu theo tháng',
      danhMucKhoanThu: 'Học phí',
      thamChieuPhapLy: 'NQ 04/2023/NQ-HĐND',
      ghiChu: '',
    },
    {
      maPhi: 'BT002',
      tenPhi: 'Bán trú hè',
      soTien: 350000,
      donViTinh: 'tháng',
      nguonThu: 'Bán trú',
      nhomPhi: 'Thu không định kỳ',
      danhMucKhoanThu: 'Bán trú',
      thamChieuPhapLy: '',
      ghiChu: 'Áp dụng tháng 6-7',
    },
  ]
  return rows.map((row) => ({ ...row, nienKhoa }))
}
